CMAKE_MINIMUM_REQUIRED(VERSION 3.24)
if (NOT ogre-next_FOUND)
    INCLUDE(FetchContent)
    FetchContent_Declare(ogre-next URL https://github.com/OGRECave/ogre-next/archive/refs/tags/v2.3.1.tar.gz)
    FetchContent_GetProperties(ogre-next)
    if (NOT ogre-next_POPULATED)
        SET(FETCHCONTENT_QUIET NO)
        FetchContent_Populate(ogre-next)
        SET(BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
        ADD_SUBDIRECTORY(${ogre-next_SOURCE_DIR} ${ogre-next_BINARY_DIR})
        SET(ogre-next_FOUND TRUE)
    endif()
endif()