CMAKE_MINIMUM_REQUIRED(VERSION 3.24)
if (NOT Asio_FOUND)
    INCLUDE(FetchContent)
    FetchContent_Declare(Asio GIT_REPOSITORY https://github.com/chriskohlhoff/asio.git GIT_SHALLOW TRUE)
    FetchContent_GetProperties(Asio)
    if (NOT Asio_POPULATED)
        SET(FETCHCONTENT_QUIET NO)
        FetchContent_Populate(Asio)
        SET(BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
        SET(Asio_FOUND TRUE)
    endif()
endif()