CMAKE_MINIMUM_REQUIRED(VERSION 3.24)
if (NOT SFML_FOUND)
    INCLUDE(FetchContent)
    FetchContent_Declare(SFML GIT_REPOSITORY https://github.com/SFML/SFML.git GIT_TAG 2.6.x)
    FetchContent_MakeAvailable(SFML)
endif()