CMAKE_MINIMUM_REQUIRED(VERSION 3.24)
if (NOT SFML_FOUND)
    INCLUDE(FetchContent)
    FetchContent_Declare(SFML URL https://github.com/SFML/SFML/archive/refs/tags/2.5.1.tar.gz)
    FetchContent_GetProperties(SFML)
    if (NOT SFML_POPULATED)
        SET(FETCHCONTENT_QUIET NO)
        FetchContent_Populate(SFML)
        SET(BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
        SET(SFML_FOUND TRUE)
    endif()
endif()
