CMAKE_MINIMUM_REQUIRED(VERSION 3.24)
if (NOT asio-cmake_FOUND AND NOT asio-cmake_POPULATED)
    INCLUDE(FetchContent)
    FetchContent_Declare(asio-cmake GIT_REPOSITORY https://github.com/kingsamchen/asio-cmake.git GIT_PROGRESS TRUE)
    set(ASIO_CMAKE_ASIO_TAG asio-1-12-2)
    FetchContent_MakeAvailable(asio-cmake)
endif()