name: CI

on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: C/C++ Clang-Format
        run: find . -regex '.*\.\(cpp\|hpp\|cc\|cxx\)' -exec clang-format --verbose -style=file -i {} \;

      # - name: Project Compilation